from __future__ import annotations

DOMAIN = "lifesmart"

DEVICE_DATA_KEY = "data"
DEVICE_ID_KEY = "me"
DEVICE_NAME_KEY = "name"
DEVICE_TYPE_KEY = "devtype"
HUB_ID_KEY = "agt"
SUBDEVICE_INDEX_KEY = "idx"

LIFESMART_SIGNAL_UPDATE_ENTITY = "lifesmart_signal_update_entity"

BINARY_SENSOR_TYPES = ["SL_GUARD", "SL_DET", "SL_PIR", "SL_SMK", "SL_WTR", "SL_GAS"]
GUARD_SENSOR_TYPES = ["SL_GUARD"]
MOTION_SENSOR_TYPES = ["SL_PIR", "SL_DET"]
GENERIC_CONTROLLER_TYPES = ["SL_UACCB", "SL_CTRL", "SL_UACC"]
LOCK_TYPES = ["SL_LOCK"]

DIGITAL_DOORLOCK_LOCK_EVENT_KEY = "E_LOCK"
DIGITAL_DOORLOCK_ALARM_EVENT_KEY = "E_ALARM"

MANUFACTURER = "LifeSmart"
